name: Pinnger Cron Job

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  ping-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Websites
        run: |
          echo "Running pinnger cron job at $(date)"
          
          # Replace YOUR_DEPLOYED_URL with your actual Vercel deployment URL
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://YOUR_DEPLOYED_URL/api/ping")
          
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Ping job completed successfully"
          else
            echo "❌ Ping job failed with status code: $RESPONSE"
            exit 1
          fi
          
      - name: Keep Health Check
        run: |
          echo "Keeping service alive with health check"
          curl -s "https://YOUR_DEPLOYED_URL/api/health"
          
      - name: Display timestamp
        run: |
          echo "Job completed at: $(date)"
